### ISSUE TITLE
not work on quasar dialog

### ISSUE THREAD

**Issue by adonisCuba** [JamieCurnow/vue-clipboard3#5] opened 2022-04-29 15:46 UTC
im not sure but when i try, it not work on quasar dialog

**Comment by YusufcanY** [comment] 2022-04-30 21:31
same in headless ui dialog

**Comment by JamieCurnow** [comment] 2022-06-06 09:40
@adonisCuba @YusufcanY, is there any chance you could make a minimal repo for me to take a look at? I'm not familiar with quasar or headless ui

**Comment by JamieCurnow** [comment] 2022-06-06 10:00
@YusufcanY here's a minimal example that is working for me with headless UI:

`vue@3.2.36`
`@headlessui/vue@1.6.4`
`vue-clipboard3@2.0.0`

```vue
<template>
  <div>
    <button @click="isOpen = !isOpen">Dialog</button>
    <Dialog :open="isOpen">
      <DialogPanel>
        <DialogTitle>Dialog title</DialogTitle>
        <DialogDescription> Dialog description </DialogDescription>

        <p>Dialog content</p>
        <button @click="toClipboard('the text')">Copy thing</button>
      </DialogPanel>
    </Dialog>
  </div>
</template>

<script>
import { ref, defineComponent } from 'vue';
import {
  Dialog,
  DialogPanel,
  DialogTitle,
  DialogDescription,
} from '@headlessui/vue';

import useClipboard from 'vue-clipboard3';

export default defineComponent({
  components: {
    Dialog,
    DialogPanel,
    DialogTitle,
    DialogDescription,
  },
  setup() {
    const isOpen = ref(false);

    const { toClipboard } = useClipboard();

    return { isOpen, toClipboard };
  },
});
</script>
```

**Comment by JamieCurnow** [comment] 2022-06-27 08:23
Closing due to lack of reproduction 😄

**Closed as completed by JamieCurnow** 2022-06-27 08:23 UTC
